version: 0.2

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh -c 6.0
  
  pre_build:
    commands:
      - ls $CODEBUILD_SRC_DIR/services/deploy/src/Demo
      - dotnet restore --verbosity minimal

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/services/deploy/src/Demo
      - |
        dotnet publish \
        --configuration release \
        --framework net6.0 \
        --output ../../DeployApi


artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - '**/*'